### PR TITLE
Integrate video animation into `raytracer-cli.jl`

### PR DESCRIPTION
**Pull request by Paolo97Gll**
Integrate the creation of the video animation, actually done by `demo/video_demo.jl`, into `raytracer-cli.jl`.

- New `animation` subcommand of the `demo` command to generate the video animation.
- The present `demo` command behavior will be moved into the `image` subcommand. 

The `demo` command will become:

```
usage: raytracer_cli.jl demo [-h] {image|animation}

Show a demo of Raytracer.jl.

commands:
  image       render a demo image of Raytracer.jl
  animation   create a demo animation of Raytracer.jl (require ffmpeg)

optional arguments:
  -h, --help  show this help message and exit
```

The `animation` subcommand will have the following options:

```
usage: raytracer_cli.jl demo animation [--force] [-t CAMERA_TYPE]
                        [-p CAMERA_POSITION] [-d SCREEN_DISTANCE]
                        [-r IMAGE_RESOLUTION] [-R RENDERER] [-a ALPHA]
                        [-g GAMMA] [-D DELTA_THETA] [-f FPS]
                        [-F OUTPUT_DIR] [-O OUTPUT_FILE] [-h]

Create a demo animation of Raytracer.jl, by generating n images with
different camera orientation and merging them into an mp4 video.
Require ffmpeg installed on local machine.

optional arguments:
  --force               force overwrite
  -h, --help            show this help message and exit

frame generation:
  -t, --camera_type CAMERA_TYPE
                        choose camera type ('perspective' or
                        'orthogonal') (default: "perspective")
  -p, --camera_position CAMERA_POSITION
                        camera position in the scene as 'X,Y,Z'
                        (default: "-1,0,0")
  -d, --screen_distance SCREEN_DISTANCE
                        only for 'perspective' camera: distance
                        between camera and screen (type: Float64,
                        default: 2.0)

frame rendering:
  -r, --image_resolution IMAGE_RESOLUTION
                        resolution of the rendered image (default:
                        "540:540")
  -R, --renderer RENDERER
                        type of renderer to use (`OnOff` or `Flat`)
                        (default: "OnOff")

frame tonemapping:
  -a, --alpha ALPHA     scaling factor for the normalization process
                        (type: Float64, default: 1.0)
  -g, --gamma GAMMA     gamma value for the tone mapping process
                        (type: Float64, default: 1.0)

animation parameter:
  -D, --delta_theta DELTA_THETA
                        Δθ in camera orientation (around z axis)
                        between each frame; the number of frames
                        generated is [360/Δθ] (type: Int64, default:
                        10)
  -f, --fps FPS         FPS (frame-per-second) of the output video
                        (type: Int64, default: 15)

files:
  -F, --output_dir OUTPUT_DIR
                        output directory (default: "demo_animation")
  -O, --output_file OUTPUT_FILE
                        name of output frames and animation without
                        extension (default: "demo")
```

Usage examples:

```
> julia raytracer_cli.jl demo animation
  Activating environment at `~/repo/Raytracer.jl/Project.toml`

-------------------------------
| Raytracer.jl animation demo |
-------------------------------
Threads number: 1

Creating directory ./demo_animation... done!
Generating 36 frames...
Progress: 100%|██████████████████████████████████████████████████████| Time: 0:04:08
Generating animation... done!
```

```
> julia --threads 8 raytracer_cli.jl demo animation --delta_theta 1 --fps 60
  Activating environment at `~/repo/Raytracer.jl/Project.toml`

-------------------------------
| Raytracer.jl animation demo |
-------------------------------
Threads number: 8

Creating directory ./demo_animation... done!
Generating 360 frames...
Progress: 100%|██████████████████████████████████████████████████████| Time: 0:29:50
Generating animation... done!
```

https://user-images.githubusercontent.com/49845775/119697924-0165a880-be51-11eb-8252-a76a2abd7c83.mp4

### CODE REVIEW

**Comment by Paolo97Gll** [comment]
Now `demo/video_demo.jl` should be deleted?

**Comment by Samuele-Colombo** [comment]
> Now `demo/video_demo.jl` should be deleted?

I think so, it is redundant and an inferior product. We should erase the entire demo directory

**Comment by Samuele-Colombo** [comment]
I also see we have the usual problem of not having much of a speedup by using thread parallelization:

```
❯ julia -t 16 raytracer_cli.jl demo animation -R Flat
  Activating environment at `~/Immagini_Fotorealistiche/Raytracer.jl/Project.toml`

-------------------------------
| Raytracer.jl animation demo |
-------------------------------
Threads number: 16

Directory ./demo_animation existing: overwrite content? [y|n] y

Creating directory ./demo_animation... done!
Generating 36 frames...
Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| Time: 0:03:08
Generating animation... done!
```
```
❯ julia raytracer_cli.jl demo animation -R Flat
  Activating environment at `~/Immagini_Fotorealistiche/Raytracer.jl/Project.toml`

-------------------------------
| Raytracer.jl animation demo |
-------------------------------
Threads number: 1

Directory ./demo_animation existing: overwrite content? [y|n] y

Creating directory ./demo_animation... done!
Generating 36 frames...
Progress: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| Time: 0:03:59
Generating animation... done!
```
it is not possible that 16 thread parallelization leads only to a a ~25% speedup on such costly computations: there must be something locking somewhere we don't know about :thinking:

**Comment by Paolo97Gll** [comment]
We should check if `ffmpeg` is installed and throw an error before starting the image generation, see: https://discourse.julialang.org/t/how-to-check-if-a-program-exists-in-a-system-using-julia/19604

**Comment by Samuele-Colombo** [comment]
There are some evident problems with the rendering, as can be seen in this video obtained with the command `julia -t 16 raytracer_cli.jl demo animation -R Flat`

https://user-images.githubusercontent.com/79973069/119957052-07b76a00-bfa2-11eb-9555-ee58c4be42da.mp4

The lower-central sphere has the wrong pattern on it (should be checkered) and a abnormal behavior. same for the central-lateral sphere, that should present 4 color stripes, not 2.

furthermore, as can be seen in the seventh frame of the video

demo_06

there are wrong superpositions of shapes.

**Comment by Paolo97Gll** [comment]
> 
> 
> We should check if `ffmpeg` is installed and throw an error before starting the image generation, see: https://discourse.julialang.org/t/how-to-check-if-a-program-exists-in-a-system-using-julia/19604

Implemented in [e6d623a](https://github.com/Paolo97Gll/Raytracer.jl/pull/19/commits/e6d623ae5b69d7cdf40c41d94503426f03c8cf72)

**Comment by Paolo97Gll** [comment]
> 
> 
> There are some evident problems with the rendering, as can be seen in this video obtained with the command `julia -t 16 raytracer_cli.jl demo animation -R Flat`
> demo.mp4
> 
> The lower-central sphere has the wrong pattern on it (should be checkered) and a abnormal behavior. same for the central-lateral sphere, that should present 4 color stripes, not 2.
> 
> furthermore, as can be seen in the seventh frame of the video
> 
> demo_06
> 
> there are wrong superpositions of shapes.

I think we should move this in another pull request, since it is beyond the context of this PR.

**Review by Samuele-Colombo — APPROVED** [review]
Except for the issue #21 (which is not related to what was implemented in this PR), it seems all right to me and I think we should merge.

**Pull request merged**
